all:
  children:
    vagrant:
      hosts:
        192.168.2.25:
          ansible_user: "afk"
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASS') }}"
          