all:
  children:
    vagrant:
      hosts:
        192.168.2.25:
          ansible_user: "afk"
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASS') }}"
    database_server:
      hosts:
        192.168.2.80:
          ansible_user: "vagrant"
          ansible_ssh_private_key_file: ~/.ssh/vagrant_key

    app_servers:
     hosts:
        192.168.2.81:
          ansible_user: "vagrant"
          ansible_ssh_private_key_file: ~/.ssh/vagrant_key
        192.168.2.82:
          ansible_user: "vagrant"
          ansible_ssh_private_key_file: ~/.ssh/vagrant_key

          