all:
  children:
    prodgeek:
      hosts:
        192.168.2.10:
          ansible_user: "afk"
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASS') }}"
          php_webserver_daemon: "nginx"
          php_default_version_debian: "7.4"