---
- hosts: vagrant

  vars_files:
    - vars/project.yml
  roles:
    - vagrant

- hosts: database_server

  vars_files:
    - vars/project.yml
    - vars/project_vault.yml
  roles:
    - mysql
    
- hosts: app_servers

  vars_files:
    - vars/project_vault.yml
  roles:
    - appserver