---
vagrant_project_folder: "vagrant_prj"
db_host: "192.168.2.80"
app1_host: "192.168.2.81"
app2_host: "192.168.2.82"
proxy_host: "192.168.2.83"

server_name: "wordpress.loc"
nginx_listen: "80"
nginx_root: "/var/www/{{ server_name }}/wordpress"
nginx_index: "index.php index.html index.htm"
nginx_server_name: "{{ server_name }} www.{{ server_name }}"
nginx_client_max_body_size: "32M"
